version: '3'
services:
    db:
        image: mysql
        container_name: smysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: pass
        restart: always


    redis:
        image: redis
        container_name: sredis
        ports:
            - "6379:6379"
        restart: always
